import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { Json } from "@/integrations/supabase/types";

export type LicenseeStatus = "active" | "inactive" | "pending" | "suspended";

export interface Licensee {
  id: string;
  code: string;
  name: string;
  legal_name: string | null;
  document_number: string | null;
  email: string | null;
  phone: string | null;
  address_street: string | null;
  address_city: string | null;
  address_state: string | null;
  address_zip: string | null;
  coverage_cities: string[] | null;
  coverage_states: string[] | null;
  business_hours: Json | null;
  status: LicenseeStatus;
  performance_score: number | null;
  total_machines: number | null;
  total_revenue: number | null;
  contract_start_date: string | null;
  contract_end_date: string | null;
  notes: string | null;
  metadata: Json | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // Extended fields added via migration
  responsavel: string | null;
  instagram: string | null;
  machines_1l: number | null;
  machines_100ml: number | null;
  tier: string | null;
  acao: string | null;
  observacoes: string | null;
  current_level: string | null;
  current_score: number | null;
}

export interface LicenseeInsert {
  name: string;
  legal_name?: string;
  document_number?: string;
  email?: string;
  phone?: string;
  address_street?: string;
  address_city?: string;
  address_state?: string;
  address_zip?: string;
  coverage_cities?: string[];
  coverage_states?: string[];
  business_hours?: Record<string, { open: string; close: string }>;
  status?: LicenseeStatus;
  contract_start_date?: string;
  contract_end_date?: string;
  notes?: string;
}

export function useLicensees(statusFilter?: LicenseeStatus | "all") {
  return useQuery({
    queryKey: ["licensees", statusFilter],
    queryFn: async () => {
      let query = supabase
        .from("licensees")
        .select("*")
        .order("created_at", { ascending: false });

      if (statusFilter && statusFilter !== "all") {
        query = query.eq("status", statusFilter);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as Licensee[];
    },
  });
}

export function useLicensee(id: string | undefined) {
  return useQuery({
    queryKey: ["licensee", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("licensees")
        .select("*")
        .eq("id", id)
        .single();
      if (error) throw error;
      return data as Licensee;
    },
    enabled: !!id,
  });
}

export function useCreateLicensee() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: LicenseeInsert & { latitude?: number; longitude?: number }) => {
      const { data: user } = await supabase.auth.getUser();
      const { latitude, longitude, ...insertData } = data;
      
      const metadata = latitude && longitude 
        ? { latitude, longitude }
        : {};

      const { data: result, error } = await supabase
        .from("licensees")
        .insert([{
          ...insertData,
          code: "TEMP", // Will be auto-generated by trigger
          metadata: metadata as Json,
          created_by: user.user?.id,
        }])
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["licensees"] });
      toast.success("Licenciado criado com sucesso!");
    },
    onError: (error: Error) => {
      toast.error("Erro ao criar licenciado: " + error.message);
    },
  });
}

export function useUpdateLicensee() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: { id: string } & Partial<LicenseeInsert>) => {
      const { data: result, error } = await supabase
        .from("licensees")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["licensees"] });
      queryClient.invalidateQueries({ queryKey: ["licensee", variables.id] });
      toast.success("Licenciado atualizado com sucesso!");
    },
    onError: (error: Error) => {
      toast.error("Erro ao atualizar licenciado: " + error.message);
    },
  });
}

export function useDeleteLicensee() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("licensees")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["licensees"] });
      toast.success("Licenciado removido com sucesso!");
    },
    onError: (error: Error) => {
      toast.error("Erro ao remover licenciado: " + error.message);
    },
  });
}

// Brazilian state capitals
const STATE_CAPITALS: Record<string, string> = {
  AC: "Rio Branco", AL: "Maceió", AP: "Macapá", AM: "Manaus", BA: "Salvador",
  CE: "Fortaleza", DF: "Brasília", ES: "Vitória", GO: "Goiânia", MA: "São Luís",
  MT: "Cuiabá", MS: "Campo Grande", MG: "Belo Horizonte", PA: "Belém",
  PB: "João Pessoa", PR: "Curitiba", PE: "Recife", PI: "Teresina", RJ: "Rio de Janeiro",
  RN: "Natal", RS: "Porto Alegre", RO: "Porto Velho", RR: "Boa Vista",
  SC: "Florianópolis", SP: "São Paulo", SE: "Aracaju", TO: "Palmas"
};

export function useLicenseeStats() {
  return useQuery({
    queryKey: ["licensee-stats"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("licensees")
        .select("status, total_machines, total_revenue, coverage_states, coverage_cities, performance_score, address_state, address_city");

      if (error) throw error;

      // Calculate unique states and cities across all licensees
      const allStates = new Set<string>();
      const allCities = new Set<string>();
      const activeCapitals = new Set<string>();
      let totalPerformance = 0;
      let performanceCount = 0;

      data.forEach((l) => {
        // Add coverage states and address state
        (l.coverage_states || []).forEach((s: string) => allStates.add(s));
        if (l.address_state) allStates.add(l.address_state);
        
        // Add coverage cities and address city
        (l.coverage_cities || []).forEach((c: string) => allCities.add(c));
        if (l.address_city) allCities.add(l.address_city);
        
        // Check if any city is a state capital
        const citiesToCheck = [...(l.coverage_cities || []), l.address_city].filter(Boolean);
        citiesToCheck.forEach((city: string) => {
          Object.entries(STATE_CAPITALS).forEach(([state, capital]) => {
            if (city?.toLowerCase().includes(capital.toLowerCase()) || capital.toLowerCase().includes(city?.toLowerCase())) {
              activeCapitals.add(capital);
            }
          });
        });
        
        if (l.performance_score) {
          totalPerformance += Number(l.performance_score);
          performanceCount++;
        }
      });

      const stats = {
        total: data.length,
        active: data.filter((l) => l.status === "active").length,
        pending: data.filter((l) => l.status === "pending").length,
        inactive: data.filter((l) => l.status === "inactive").length,
        totalMachines: data.reduce((sum, l) => sum + (l.total_machines || 0), 0),
        totalRevenue: data.reduce((sum, l) => sum + Number(l.total_revenue || 0), 0),
        totalStates: allStates.size,
        totalCities: allCities.size,
        totalCapitals: activeCapitals.size,
        activeStates: Array.from(allStates),
        activeCapitals: Array.from(activeCapitals),
        avgPerformance: performanceCount > 0 ? totalPerformance / performanceCount : 0,
      };

      return stats;
    },
  });
}
