import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": Deno.env.get("ALLOWED_ORIGIN") ?? "https://carbohub.com.br",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Validate authorization - only allow calls with valid Authorization header
    // This function should only be called by internal cron jobs or admin users
    const authHeader = req.headers.get("authorization");
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    
    // Check if the request has a valid authorization header
    if (!authHeader) {
      console.error("Missing authorization header");
      return new Response(
        JSON.stringify({ error: "Unauthorized - missing authorization header" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    
    const token = authHeader.replace("Bearer ", "");
    
    // Validate the token is either the anon key (from cron) or a valid JWT
    if (token !== supabaseAnonKey) {
      // If not anon key, verify it's a valid JWT from an admin/manager
      const authClient = createClient(supabaseUrl, supabaseAnonKey!, {
        global: { headers: { Authorization: authHeader } }
      });
      
      const { data: claims, error: claimsError } = await authClient.auth.getClaims(token);
      
      if (claimsError || !claims?.claims?.sub) {
        console.error("Invalid JWT token:", claimsError?.message);
        return new Response(
          JSON.stringify({ error: "Unauthorized - invalid token" }),
          { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      // Verify user is admin or manager
      const { data: userRoles } = await authClient
        .from("user_roles")
        .select("role")
        .eq("user_id", claims.claims.sub);
      
      const isAuthorized = userRoles?.some(r => 
        ["admin", "manager"].includes(r.role)
      );
      
      if (!isAuthorized) {
        console.error("User not authorized to trigger recurring orders processing");
        return new Response(
          JSON.stringify({ error: "Forbidden - insufficient permissions" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const today = new Date().toISOString().split("T")[0];
    console.log(`Processing recurring orders for date: ${today}`);

    // Find all recurring orders due today or earlier
    const { data: dueOrders, error: fetchError } = await supabase
      .from("carboze_orders")
      .select("*")
      .eq("is_recurring", true)
      .eq("status", "delivered")
      .lte("next_delivery_date", today);

    if (fetchError) throw fetchError;

    console.log(`Found ${dueOrders?.length || 0} recurring orders to process`);

    const createdOrders = [];
    const notifications = [];

    for (const order of dueOrders || []) {
      // Calculate next delivery date first
      const nextDate = new Date(order.next_delivery_date);
      nextDate.setDate(nextDate.getDate() + (order.recurrence_interval_days || 30));
      const nextDeliveryDate = nextDate.toISOString().split("T")[0];

      // Create a new order based on the recurring template
      const newOrderData = {
        customer_name: order.customer_name,
        customer_email: order.customer_email,
        customer_phone: order.customer_phone,
        licensee_id: order.licensee_id,
        delivery_address: order.delivery_address,
        delivery_city: order.delivery_city,
        delivery_state: order.delivery_state,
        delivery_zip: order.delivery_zip,
        items: order.items,
        subtotal: order.subtotal,
        shipping_cost: order.shipping_cost,
        discount: order.discount,
        total: order.total,
        has_commission: order.has_commission,
        commission_rate: order.commission_rate,
        commission_amount: order.commission_amount,
        notes: order.notes,
        order_type: "recorrente",
        is_recurring: true,
        recurrence_interval_days: order.recurrence_interval_days,
        next_delivery_date: nextDeliveryDate,
        parent_order_id: order.parent_order_id || order.id,
        order_number: "", // Will be auto-generated by trigger
        created_by: order.created_by,
      };

      const { data: newOrder, error: insertError } = await supabase
        .from("carboze_orders")
        .insert(newOrderData)
        .select()
        .single();

      if (insertError) {
        console.error(`Error creating order from ${order.id}:`, insertError);
        continue;
      }

      createdOrders.push(newOrder);

      // Update the parent order with reference to the new order
      await supabase
        .from("carboze_orders")
        .update({ last_recurrence_order_id: newOrder.id })
        .eq("id", order.id);

      // Add status history for the new order
      await supabase.from("order_status_history").insert({
        order_id: newOrder.id,
        status: "pending",
        notes: `Pedido recorrente gerado automaticamente a partir de ${order.order_number}`,
      });

      // Create notification for managers
      const { data: managers } = await supabase
        .from("user_roles")
        .select("user_id")
        .in("role", ["admin", "manager"]);

      for (const manager of managers || []) {
        notifications.push({
          user_id: manager.user_id,
          type: "recurring_order",
          title: "Novo pedido recorrente gerado",
          body: `Pedido ${newOrder.order_number} criado automaticamente para ${order.customer_name}`,
          reference_type: "carboze_order",
          reference_id: newOrder.id,
        });
      }
    }

    // Insert all notifications
    if (notifications.length > 0) {
      await supabase.from("notifications").insert(notifications);
    }

    // Also check for orders with upcoming delivery dates (within 3 days) and notify
    const threeDaysFromNow = new Date();
    threeDaysFromNow.setDate(threeDaysFromNow.getDate() + 3);
    const upcomingDate = threeDaysFromNow.toISOString().split("T")[0];

    const { data: upcomingOrders } = await supabase
      .from("carboze_orders")
      .select("*")
      .eq("is_recurring", true)
      .neq("status", "cancelled")
      .neq("status", "delivered")
      .gte("next_delivery_date", today)
      .lte("next_delivery_date", upcomingDate);

    const upcomingNotifications = [];
    const { data: managers } = await supabase
      .from("user_roles")
      .select("user_id")
      .in("role", ["admin", "manager"]);

    for (const order of upcomingOrders || []) {
      for (const manager of managers || []) {
        // Check if notification already exists for today
        const { data: existing } = await supabase
          .from("notifications")
          .select("id")
          .eq("user_id", manager.user_id)
          .eq("reference_id", order.id)
          .eq("type", "upcoming_recurring")
          .gte("created_at", today);

        if (!existing || existing.length === 0) {
          const daysUntil = Math.ceil(
            (new Date(order.next_delivery_date).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24)
          );
          upcomingNotifications.push({
            user_id: manager.user_id,
            type: "upcoming_recurring",
            title: "Pedido recorrente próximo",
            body: `Pedido ${order.order_number} para ${order.customer_name} programado para ${daysUntil} dia(s)`,
            reference_type: "carboze_order",
            reference_id: order.id,
          });
        }
      }
    }

    if (upcomingNotifications.length > 0) {
      await supabase.from("notifications").insert(upcomingNotifications);
    }

    return new Response(
      JSON.stringify({
        success: true,
        created_orders: createdOrders.length,
        notifications_sent: notifications.length + upcomingNotifications.length,
        upcoming_orders_notified: upcomingOrders?.length || 0,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("Error processing recurring orders:", error);
    return new Response(
      JSON.stringify({ error: errorMessage }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
