import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { 
  Plus, 
  Users, 
  Store, 
  ShoppingCart, 
  RefreshCw,
  ArrowLeft,
  CheckCircle,
  Loader2,
  Building2,
  FileText,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

type OSOriginType = "licensee" | "pdv" | "spot_sale" | "recurring_sale";

interface OriginOption {
  value: OSOriginType;
  label: string;
  description: string;
  icon: React.ReactNode;
  color: string;
}

const OS_ORIGINS: OriginOption[] = [
  {
    value: "licensee",
    label: "Licenciado",
    description: "OP vinculada a um licenciado parceiro",
    icon: <Users className="h-5 w-5" />,
    color: "bg-carbo-green/10 border-carbo-green/30 hover:bg-carbo-green/20 text-carbo-green",
  },
  {
    value: "pdv",
    label: "PDV CarboZé",
    description: "OP de reposição ou operação de PDV",
    icon: <Store className="h-5 w-5" />,
    color: "bg-amber-500/10 border-amber-500/30 hover:bg-amber-500/20 text-amber-600",
  },
  {
    value: "spot_sale",
    label: "Venda Spot",
    description: "Venda avulsa sem recorrência",
    icon: <ShoppingCart className="h-5 w-5" />,
    color: "bg-blue-500/10 border-blue-500/30 hover:bg-blue-500/20 text-blue-600",
  },
  {
    value: "recurring_sale",
    label: "Venda Recorrente",
    description: "Pedido com entrega programada",
    icon: <RefreshCw className="h-5 w-5" />,
    color: "bg-purple-500/10 border-purple-500/30 hover:bg-purple-500/20 text-purple-600",
  },
];

interface CreateOSDialogProps {
  trigger?: React.ReactNode;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  onSuccess?: () => void;
}

export function CreateOSDialog({ 
  trigger, 
  defaultOpen = false,
  onOpenChange,
  onSuccess 
}: CreateOSDialogProps) {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [open, setOpen] = useState(defaultOpen);
  const [step, setStep] = useState<"origin" | "form" | "success">("origin");
  const [selectedOrigin, setSelectedOrigin] = useState<OSOriginType | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [createdOS, setCreatedOS] = useState<{ osNumber: string; id: string } | null>(null);

  // Fetch licensees for selection
  const { data: licensees = [] } = useQuery({
    queryKey: ["licensees-select"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("licensees")
        .select("id, name, code")
        .eq("status", "active")
        .order("name");
      if (error) throw error;
      return data;
    },
    enabled: selectedOrigin === "licensee",
  });

  // Fetch PDVs for selection (from machines table)
  const { data: pdvs = [] } = useQuery({
    queryKey: ["pdvs-select"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("machines")
        .select("id, machine_id, location_address, location_city")
        .eq("status", "operational")
        .order("machine_id");
      if (error) throw error;
      return data;
    },
    enabled: selectedOrigin === "pdv",
  });

  const handleOpenChange = (isOpen: boolean) => {
    setOpen(isOpen);
    onOpenChange?.(isOpen);
    if (!isOpen) {
      setTimeout(() => {
        setStep("origin");
        setSelectedOrigin(null);
        setCreatedOS(null);
      }, 200);
    }
  };

  const handleOriginSelect = (origin: OSOriginType) => {
    setSelectedOrigin(origin);
    setStep("form");
  };

  const handleBack = () => {
    setStep("origin");
    setSelectedOrigin(null);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!user || !selectedOrigin) return;

    setIsCreating(true);
    const formData = new FormData(e.currentTarget);

    try {
      const osData: any = {
        title: formData.get("title") as string,
        description: formData.get("description") as string,
        priority: parseInt(formData.get("priority") as string) || 2,
        created_by: user.id,
        os_number: "", // Auto-generated by trigger
        origin_type: selectedOrigin,
      };

      // Add specific references based on origin
      if (selectedOrigin === "licensee") {
        osData.licensee_id = formData.get("licensee_id");
      } else if (selectedOrigin === "pdv") {
        osData.machine_id = formData.get("pdv_id");
      } else if (selectedOrigin === "recurring_sale") {
        osData.is_recurring = true;
      }

      const { data, error } = await supabase
        .from("service_orders")
        .insert(osData)
        .select("id, os_number")
        .single();

      if (error) throw error;

      setCreatedOS({ osNumber: data.os_number, id: data.id });
      setStep("success");
      toast.success("OP criada com sucesso!");
      onSuccess?.();
    } catch (error: any) {
      toast.error("Erro ao criar OP: " + error.message);
    } finally {
      setIsCreating(false);
    }
  };

  const handleViewOS = () => {
    if (createdOS) {
      navigate(`/os/${createdOS.id}`);
      handleOpenChange(false);
    }
  };

  const selectedOriginConfig = OS_ORIGINS.find(o => o.value === selectedOrigin);

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      {trigger && <DialogTrigger asChild>{trigger}</DialogTrigger>}
      <DialogContent className="max-w-lg">
        {step === "origin" ? (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-xl">
                <Plus className="h-5 w-5 text-carbo-green" />
                Nova Ordem de Produção
              </DialogTitle>
              <DialogDescription>
                Selecione a origem da OP para iniciar o fluxo
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-3 py-4">
              {OS_ORIGINS.map((origin) => (
                <button
                  key={origin.value}
                  onClick={() => handleOriginSelect(origin.value)}
                  className={cn(
                    "flex items-center gap-4 p-4 rounded-xl border-2 transition-all duration-200 text-left",
                    origin.color
                  )}
                >
                  <div className={cn(
                    "h-12 w-12 rounded-xl flex items-center justify-center bg-background border",
                    origin.color.split(" ")[0].replace("/10", "/20")
                  )}>
                    {origin.icon}
                  </div>
                  <div className="flex-1">
                    <p className="font-semibold text-foreground">{origin.label}</p>
                    <p className="text-sm text-muted-foreground">{origin.description}</p>
                  </div>
                </button>
              ))}
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={() => handleOpenChange(false)}>
                Cancelar
              </Button>
            </DialogFooter>
          </>
        ) : step === "form" ? (
          <>
            <DialogHeader>
              <div className="flex items-center gap-2 mb-2">
                <button 
                  onClick={handleBack}
                  className="text-sm text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1"
                >
                  <ArrowLeft className="h-3 w-3" />
                  Voltar
                </button>
              </div>
              <DialogTitle className="flex items-center gap-3">
                <div className={cn(
                  "h-10 w-10 rounded-xl flex items-center justify-center bg-background border",
                  selectedOriginConfig?.color.split(" ")[0]
                )}>
                  {selectedOriginConfig?.icon}
                </div>
                <div>
                  <span className="block">OP - {selectedOriginConfig?.label}</span>
                  <span className="text-sm font-normal text-muted-foreground">
                    {selectedOriginConfig?.description}
                  </span>
                </div>
              </DialogTitle>
            </DialogHeader>

            <form onSubmit={handleSubmit} className="space-y-4 pt-2">
              {/* Seletor de Licenciado */}
              {selectedOrigin === "licensee" && (
                <div className="space-y-2">
                  <Label htmlFor="licensee_id" className="flex items-center gap-2">
                    <Building2 className="h-4 w-4 text-muted-foreground" />
                    Licenciado *
                  </Label>
                  <Select name="licensee_id" required>
                    <SelectTrigger className="h-11">
                      <SelectValue placeholder="Selecione o licenciado" />
                    </SelectTrigger>
                    <SelectContent>
                      {licensees.map((lic) => (
                        <SelectItem key={lic.id} value={lic.id}>
                          <span className="flex items-center gap-2">
                            <code className="text-xs bg-muted px-1 rounded">{lic.code}</code>
                            {lic.name}
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              {/* Seletor de PDV */}
              {selectedOrigin === "pdv" && (
                <div className="space-y-2">
                  <Label htmlFor="pdv_id" className="flex items-center gap-2">
                    <Store className="h-4 w-4 text-muted-foreground" />
                    PDV / Máquina *
                  </Label>
                  <Select name="pdv_id" required>
                    <SelectTrigger className="h-11">
                      <SelectValue placeholder="Selecione o PDV" />
                    </SelectTrigger>
                    <SelectContent>
                      {pdvs.map((pdv) => (
                        <SelectItem key={pdv.id} value={pdv.id}>
                          <span className="flex items-center gap-2">
                            <code className="text-xs bg-muted px-1 rounded">{pdv.machine_id}</code>
                            {pdv.location_city || pdv.location_address || "Sem endereço"}
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div className="space-y-2">
                <Label htmlFor="title" className="flex items-center gap-2">
                  <FileText className="h-4 w-4 text-muted-foreground" />
                  Título da OP *
                </Label>
                <Input
                  id="title"
                  name="title"
                  placeholder="Ex: Instalação CarboVapt - Cliente ABC"
                  required
                  className="h-11"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Descrição</Label>
                <Textarea
                  id="description"
                  name="description"
                  placeholder="Detalhes adicionais da ordem de produção..."
                  rows={3}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="priority">Prioridade</Label>
                <Select name="priority" defaultValue="2">
                  <SelectTrigger className="h-11">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">🟢 Baixa</SelectItem>
                    <SelectItem value="2">🔵 Normal</SelectItem>
                    <SelectItem value="3">🟡 Média</SelectItem>
                    <SelectItem value="4">🟠 Alta</SelectItem>
                    <SelectItem value="5">🔴 Urgente</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Info adicional para recorrência */}
              {selectedOrigin === "recurring_sale" && (
                <div className="p-4 bg-purple-500/5 border border-purple-500/20 rounded-xl">
                  <p className="text-sm text-muted-foreground">
                    <strong className="text-foreground">Venda Recorrente:</strong> Esta OP será 
                     marcada como recorrente. Configure os detalhes de programação após a criação.
                  </p>
                </div>
              )}

              <DialogFooter className="pt-4 border-t">
                <Button type="button" variant="outline" onClick={() => handleOpenChange(false)}>
                  Cancelar
                </Button>
                <Button type="submit" disabled={isCreating} className="carbo-gradient text-white">
                  {isCreating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Criando...
                    </>
                  ) : (
                    <>
                      <Plus className="mr-2 h-4 w-4" />
                      Criar OP
                    </>
                  )}
                </Button>
              </DialogFooter>
            </form>
          </>
        ) : (
          <>
            <DialogHeader className="text-center">
              <div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-carbo-green/20 to-carbo-blue/20">
                <CheckCircle className="h-10 w-10 text-carbo-green" />
              </div>
               <DialogTitle className="text-xl">OP Criada com Sucesso!</DialogTitle>
               <DialogDescription>
                 A ordem de produção foi criada e está pronta para execução
              </DialogDescription>
            </DialogHeader>

            <div className="bg-muted/50 rounded-xl p-5 space-y-3 my-4">
              <div className="flex items-center justify-between">
                <span className="text-sm text-muted-foreground">Número:</span>
                <code className="font-mono font-bold text-lg text-primary bg-primary/10 px-3 py-1 rounded">
                  {createdOS?.osNumber}
                </code>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-sm text-muted-foreground">Origem:</span>
                <div className="flex items-center gap-2">
                  {selectedOriginConfig?.icon}
                  <span className="font-medium">{selectedOriginConfig?.label}</span>
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <Button variant="outline" className="flex-1" onClick={() => handleOpenChange(false)}>
                Fechar
              </Button>
              <Button className="flex-1 carbo-gradient text-white" onClick={handleViewOS}>
                Ver OP
              </Button>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
